# services:
#   fastapi:
#     build: .
#     container_name: utsav0987/rentals-backend-image
#     ports:
#       - "8000:8000"
#     depends_on:
#       db:
#         condition: service_healthy
#     env_file:
#       - .env  # Load environment variables from the .env file
#     environment:
#       - DB_USER=${DB_USER}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_NAME=${DB_NAME}
#       - DB_HOST=db
#       - DB_PORT=${DB_PORT}


#   db:
#     image: postgres:16
#     container_name: utsav0987/rentals-db-repo
#     env_file:
#       - .env
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   postgres_data:

services:
  fastapi:
    image: utsav0987/rentals-backend-image  # Use the image from Docker Hub
    container_name: rentals_backend_container  # Local container name
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}

  db:
    image: utsav0987/rentals-db-repo  # Use the image from Docker Hub
    container_name: rentals_db_container  # Local container name
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
